package transfer.enums;

public enum Operation {
	PRIJAVI_ZAPOSLENI,
	
	KREIRAJ_KNJIGA,
	OBRISI_KNJIGA,
	PROMENI_KNJIGA,
	VRATI_LISTU_KNJIGA,

	KREIRAJ_ZAPOSLENI,
	OBRISI_ZAPOSLENI,
	PROMENI_ZAPOSLENI,
	VRATI_LISTU_ZAPOSLENI,

	KREIRAJ_KUPAC,
	OBRISI_KUPAC,
	PROMENI_KUPAC,
	VRATI_LISTU_KUPAC,

	KREIRAJ_PRAVNO_LICE,
	OBRISI_PRAVNO_LICE,
	PROMENI_PRAVNO_LICE,
	VRATI_LISTU_PRAVNO_LICE,

	KREIRAJ_FIZICKO_LICE,
	OBRISI_FIZICKO_LICE,
	PROMENI_FIZICKO_LICE,
	VRATI_LISTU_FIZICKO_LICE,

	KREIRAJ_RACUN,
	OBRISI_RACUN,
	PROMENI_RACUN,
	VRATI_LISTU_RACUN,

	KREIRAJ_SMENA,
	OBRISI_SMENA,
	PROMENI_SMENA,
	VRATI_LISTU_SMENA,
	
}
