package transfer.enums;

public enum Operation {
	KREIRAJ_FIZICKO_LICE,
	KREIRAJ_KNJIGA,
	KREIRAJ_KUPAC,
	KREIRAJ_PRAVNO_LICE,
	KREIRAJ_RACUN,
	KREIRAJ_ZAPOSLENI,
	
	OBRISI_FIZICKO_LICE,
	OBRISI_KNJIGA,
	OBRISI_KUPAC,
	OBRISI_PRAVNO_LICE,
	OBRISI_RACUN,
	OBRISI_ZAPOSLENI,

	PRETRAZI_FIZICKO_LICE,
	PRETRAZI_KNJIGA,
	PRETRAZI_KUPAC,
	PRETRAZI_PRAVNO_LICE,
	PRETRAZI_RACUN,
	PRETRAZI_SMENA,
	PRETRAZI_ZAPOSLENI,

	PRIJAVI_ZAPOSLENI,

	PROMENI_FIZICKO_LICE,
	PROMENI_KNJIGA,
	PROMENI_KUPAC,
	PROMENI_PRAVNO_LICE,
	PROMENI_RACUN,
	PROMENI_SMENA,
	PROMENI_ZAPOSLENI,

	UBACI_SMENA,
	
	VRATI_LISTU_FIZICKO_LICE,
	VRATI_LISTU_KNJIGA,
	VRATI_LISTU_KUPAC,
	VRATI_LISTU_PRAVNO_LICE,
	VRATI_LISTU_RACUN,
	VRATI_LISTU_SMENA,

	VRATI_LISTU_SVI_KNJIGA,
	VRATI_LISTU_SVI_KUPAC,
	VRATI_LISTU_SVI_SMENA,
	VRATI_LISTU_SVI_ZAPOSLENI,

	VRATI_LISTU_ZAPOSLENI,
}
